development:
  adapter: mysql
  database: socialactions_development
  username: root
  password: 
  host: 127.0.0.1

test:
  adapter: mysql
  database: socialactions_test
  username: root
  password: 
  host: 127.0.0.1
  
production:
  adapter: mysql
  database: socialactions_production
  username: root
  password: 
  host: 127.0.0.1