development: &development
  adapter: mysql
  database: socialactions_development
  username: twg
  password: twgRulez
  host: 127.0.0.1

test:
  <<: *development
  database: socialactions_test

production:
  <<: *development
  database: socialactions_production
